test_data={'image_png_file': WindowsPath('testdata/files/image.png')}
http_client={'url': HttpUrl('http://localhost:8000/'), 'timeout': 4.0}
allure_results_dir=allure-results
System=Windows
SystemRelease=10
PythonVersion=3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]